In [ ]:
1. create a friend_names.csv file delimiter(,)

In [3]:
import pandas as pd

In [5]:
df1_friends=pd.read_csv(r"C:\Users\hp\sowjanya_2026\friend_names.csv file.txt",sep=",")

In [7]:
df1_friends

  friendname      quality
0    meghana     creative
1     anusha         kind
2    naveena        funny
3  spandhana        smart
4   prasanna  hardworking
5     jhansi        loyal
6    bhavana       caring
7    dayakar      helpful
8      reddy       honest
9       ammu     friendly

In [9]:
df1_friends.shape

(10, 2)

In [13]:
df1_friends.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   friendname  10 non-null     object
 1   quality     10 non-null     object
dtypes: object(2)
memory usage: 292.0+ bytes

In [17]:
df1_friends.columns

Index(['friendname', 'quality'], dtype='object')

In [19]:
df1_friends.describe()

       friendname   quality
count          10        10
unique         10        10
top       meghana  creative
freq            1         1

In [21]:
df1_friends.head()

  friendname      quality
0    meghana     creative
1     anusha         kind
2    naveena        funny
3  spandhana        smart
4   prasanna  hardworking

In [ ]:
2.create a family_members.txt file delimiter(*)

In [31]:
df2_family= pd.read_csv(r"C:\Users\hp\sowjanya_2026\family_members.txt file.txt",sep="*")

In [33]:
df2_family

   familymembername          relation
0          jayapaul            father
1     rangasarojini            mother
2        rajakumari      eldestsister
3  venkataramanayya   bigbrotherinlaw
4            mahima             niece
5         sunilraju           brother
6           meghana     sister_in_law
7       yonafrancis            nephew
8            salomi            sister
9         anilkumar           husband

In [37]:
df2_family.shape

(10, 2)

In [39]:
df2_family.columns

Index(['familymembername', 'relation'], dtype='object')

In [41]:
df2_family.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   familymembername  10 non-null     object
 1   relation          10 non-null     object
dtypes: object(2)
memory usage: 292.0+ bytes

In [43]:
df2_family.describe()

       familymembername relation
count                10       10
unique               10       10
top            jayapaul   father
freq                  1        1

In [ ]:
3.create a vegfood_items.txt file delimiter(|)

In [47]:
df3_veg=pd.read_csv(r"C:\Users\hp\sowjanya_2026\vegfood_items.txt file.txt",sep="|")

In [49]:
df3_veg

            vegfoodname     taste
0  paneer butter masala     spicy
1             dal tadka    savory
2          palak paneer      mild
3             aloo gobi     spicy
4           masala dosa     tangy
5     vegetable biryani  fragrant
6         chole bhature     spicy
7          Malaki kofta     sweet
8       gobi manchurian     spicy
9       mixed veg curry    savory

In [51]:
df3_veg.shape

(10, 2)

In [53]:
df3_veg.columns

Index(['vegfoodname', 'taste'], dtype='object')

In [55]:
df3_veg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   vegfoodname  10 non-null     object
 1   taste        10 non-null     object
dtypes: object(2)
memory usage: 292.0+ bytes

In [59]:
df3_veg.describe()

                 vegfoodname  taste
count                     10     10
unique                    10      6
top     paneer butter masala  spicy
freq                       1      4

In [ ]:
4.create a nonvegfood_items.txt file delimiter(|)

In [61]:
df4_nonveg=pd.read_csv(r"C:\Users\hp\sowjanya_2026\nonvegfood_items.txt file.txt",sep="|")

In [63]:
df4_nonveg

     nonvegfoodname    taste
0   chicken biryani    spicy
1          fish fry   crispy
2      mutton curry     rich
3    butter chicken   creamy
4         egg roast    tangy
5      prawn masala   savory
6      grilled fish    smoky
7        chicken 65      hot
8       keema matar    spicy
9  tandoori chicken  charred

In [65]:
df4_nonveg.shape

(10, 2)

In [67]:
df4_nonveg.columns

Index(['nonvegfoodname', 'taste'], dtype='object')

In [69]:
df4_nonveg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nonvegfoodname  10 non-null     object
 1   taste           10 non-null     object
dtypes: object(2)
memory usage: 292.0+ bytes

In [71]:
df4_nonveg.describe()

         nonvegfoodname  taste
count                10     10
unique               10      9
top     chicken biryani  spicy
freq                  1      2

In [ ]:
5.create a month_names.txt file delimiter(&)

In [73]:
df5_month=pd.read_csv(r"C:\Users\hp\sowjanya_2026\month_names.txt file.txt",sep="&")

In [75]:
df5_month

   monthname      season
0    january      winter
1   february      winter
2      march      spring
3      april      spring
4        may      summer
5       june      summer
6       july     monsoon
7     august     monsoon
8   septmber      autumn
9    October      autumn
10  november  pre-winter
11  december      winter

In [77]:
df5_month.shape

(12, 2)

In [79]:
df5_month.columns

Index(['monthname', 'season'], dtype='object')

In [81]:
df5_month.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   monthname  12 non-null     object
 1   season     12 non-null     object
dtypes: object(2)
memory usage: 324.0+ bytes

In [83]:
df5_month.describe()

       monthname  season
count         12      12
unique        12       6
top      january  winter
freq           1       3

In [ ]:
6. create a colours_names.txt file delimiter(^)

In [85]:
df6_colours=pd.read_csv(r"C:\Users\hp\sowjanya_2026\colours_names.txt file.txt",sep="^")

In [87]:
df6_colours

   colourname_in_english colourname_in_hindi colourname_in_telugu
0                    red                 lal                erupu
1                   blue               neela               neelam
2                  green                hara            akupachha
3                 yellow               peela               pasupu
4                  white               safed               telupu
5                  black                kala              nallapu
6                   pink              gulabi               gulabi
7                 orange             narangi              narangi
8                  brown               bhura              godhuma
9                   grey              sileti             boodidha
10                purple            baingani              vankaya
11                  gold             sunehra              bangaru

In [89]:
df6_colours.shape

(12, 3)

In [91]:
df6_colours.columns

Index(['colourname_in_english', 'colourname_in_hindi', 'colourname_in_telugu'], dtype='object')

In [93]:
df6_colours.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   colourname_in_english  12 non-null     object
 1   colourname_in_hindi    12 non-null     object
 2   colourname_in_telugu   12 non-null     object
dtypes: object(3)
memory usage: 420.0+ bytes

In [95]:
df6_colours.describe()

       colourname_in_english colourname_in_hindi colourname_in_telugu
count                     12                  12                   12
unique                    12                  12                   12
top                      red                 lal                erupu
freq                       1                   1                    1

In [ ]:
7.create a friend_names.xls file

In [97]:
df7_friends=pd.read_excel(r"C:\Users\hp\sowjanya_2026\friend_names.xls file.xlsx")

In [99]:
df7_friends

  FriendName      Quality
0    meghana     creative
1     anusha         kind
2    naveena        funny
3  spandhana        smart
4   prasanna  hardworhing
5     jhansi        loyal
6    bhavana       caring
7    dayakar      helpful
8      reddy       honest
9       ammu     friendly

In [ ]:
basic checks:

In [101]:
df7_friends.shape

(10, 2)

In [103]:
df7_friends.columns

Index(['FriendName', 'Quality'], dtype='object')

In [105]:
df7_friends.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   FriendName  10 non-null     object
 1   Quality     10 non-null     object
dtypes: object(2)
memory usage: 292.0+ bytes

In [107]:
df7_friends.describe()

       FriendName   Quality
count          10        10
unique         10        10
top       meghana  creative
freq            1         1

In [ ]:
8. create a family_mebers.xls file

In [109]:
df8_family=pd.read_excel(r"C:\Users\hp\sowjanya_2026\family_members.xls file.xlsx")

In [111]:
df8_family

  FamilyMemberName     Relation
0         jayapaul       father
1    rangasarojini       mother
2       rajakumari  eldersister
3    venkataramana  brotherilla
4           mahima        niece
5        sunilraju      brother
6          meghana   sisterilla
7             yona       nephew
8           salomi       sister
9        anilkumar      husband

In [113]:
df8_family.shape

(10, 2)

In [115]:
df8_family.columns

Index(['FamilyMemberName', 'Relation'], dtype='object')

In [117]:
df8_family.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   FamilyMemberName  10 non-null     object
 1   Relation          10 non-null     object
dtypes: object(2)
memory usage: 292.0+ bytes

In [119]:
df8_family.describe()

       FamilyMemberName Relation
count                10       10
unique               10       10
top            jayapaul   father
freq                  1        1

In [ ]:
9. create a vegfood_items.xlsx file

In [121]:
df9_veg=pd.read_excel(r"C:\Users\hp\sowjanya_2026\Vegfood_items.xlsx file.xlsx")

In [123]:
df9_veg

            VegFoodName     Taste
0  paneer butter masala     spicy
1             dal tadka    savory
2          palak panner      mild
3             aolo gobi     spicy
4           masala dosa     tangy
5     vegetable biryani  fragrant
6         chole bhature     spicy
7          malaki kofta     sweet
8      gobi manchuriyan     spicy
9       mixed veg curry    savory

In [125]:
df9_veg.shape

(10, 2)

In [127]:
df9_veg.columns

Index(['VegFoodName', 'Taste'], dtype='object')

In [129]:
df9_veg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   VegFoodName  10 non-null     object
 1   Taste        10 non-null     object
dtypes: object(2)
memory usage: 292.0+ bytes

In [131]:
df9_veg.describe()

                 VegFoodName  Taste
count                     10     10
unique                    10      6
top     paneer butter masala  spicy
freq                       1      4

In [ ]:
10.create a nonvegfood_items.xlsx file

In [133]:
df10_nonveg=pd.read_excel(r"C:\Users\hp\sowjanya_2026\NonVegfood_items.xlsx file.xlsx")

In [135]:
df10_nonveg

     NonVegFoodName    Taste
0   chicken biryani    spicy
1           fishfry   crispy
2     mutton curryy     rich
3    butter chicken    cremy
4         egg roast    tangy
5      prawn masala   savory
6      grilled fish    smoky
7        chicken 65      hot
8       keema matar    spicy
9  tandoori chicken  charred

In [137]:
df10_nonveg.shape

(10, 2)

In [139]:
df10_nonveg.columns

Index(['NonVegFoodName', 'Taste'], dtype='object')

In [141]:
df10_nonveg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   NonVegFoodName  10 non-null     object
 1   Taste           10 non-null     object
dtypes: object(2)
memory usage: 292.0+ bytes

In [143]:
df10_nonveg.describe()

         NonVegFoodName  Taste
count                10     10
unique               10      9
top     chicken biryani  spicy
freq                  1      2

In [ ]:
11. create a month_names.xlsx file

In [145]:
df11_month=pd.read_excel(r"C:\Users\hp\sowjanya_2026\month_names.xlsx file.xlsx")

In [147]:
df11_month

   MonthName    Season
0    january    winter
1   february    winter
2      march    spring
3      april    spring
4        may    summer
5       june    summer
6       july  moonsoon
7     august  moonsoon
8   septmber    autumn
9    October    autumn
10  november    winter
11  december    winter

In [149]:
df11_month.shape

(12, 2)

In [151]:
df11_month.columns

Index(['MonthName', 'Season'], dtype='object')

In [153]:
df11_month.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   MonthName  12 non-null     object
 1   Season     12 non-null     object
dtypes: object(2)
memory usage: 324.0+ bytes

In [155]:
df11_month.describe()

       MonthName  Season
count         12      12
unique        12       5
top      january  winter
freq           1       4

In [ ]:
12. create a colours_names.xlsx file

In [159]:
df12_colours=pd.read_excel(r"C:\Users\hp\sowjanya_2026\colours_names.xlsx file.xlsx")

In [161]:
df12_colours

   colourName_in_English colourName_in_Hindhi colourName_in_Teluhu
0                    red                  lal                erupu
1                   blue                neela               neelam
2                  green                 hara            akupachha
3                 yellow                peela               pasupu
4                  white                safed               telupu
5                  black                 kala              nallapu
6                   pink               gulabi               gulabi
7                 orange              narangi              narangi
8                  brown                bhura              godhuma
9                   grey               sileti             boodidha
10                purple             baingani              vankaya
11                  gold              sunehra              bangaru

In [163]:
df12_colours.shape

(12, 3)

In [165]:
df12_colours.columns

Index(['colourName_in_English', 'colourName_in_Hindhi',
       'colourName_in_Teluhu'],
      dtype='object')

In [167]:
df12_colours.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   colourName_in_English  12 non-null     object
 1   colourName_in_Hindhi   12 non-null     object
 2   colourName_in_Teluhu   12 non-null     object
dtypes: object(3)
memory usage: 420.0+ bytes

In [169]:
df12_colours.describe()

       colourName_in_English colourName_in_Hindhi colourName_in_Teluhu
count                     12                   12                   12
unique                    12                   12                   12
top                      red                  lal                erupu
freq                       1                    1                    1